version: "3.7"

networks:
  web:
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - web
    expose:
      - "80"
