version: "3.7"
services:
  # Media Player
  plex:
    image: "plexinc/pms-docker:latest"
    # image: linuxserver/plex
    container_name: plex
    networks:
      - traefik
    restart: unless-stopped
    # network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    # expose:
    #   - "32400"
    #   - "3005"
    #   - "8324"
    #   - "32469"
    #   - "1900"
    #   - "32410"
    #   - "32412"
    #   - "32413"
    #   - "32414"
    environment:
      - ADVERTISE_IP=http://192.168.1.200:32400/
      - TZ=America/New_York
      - PLEX_CLAIM="claim-qxVKRrNKy9x1WQXzEJxD"
      - PLEX_UID=1000
      - PLEX_GID=1000
      # - PUID=1000
      # - PGID=1000
      # - VERSION=docker
      # - UMASK_SET=022 #optional
      # - PLEX_CLAIM="claim-qxVKRrNKy9x1WQXzEJxD"
    volumes:
      - /mnt/media/config/plex:/config
      - /mnt/media/transcode:/transcode
      - /mnt/media/libraries/shows:/data/tvshows
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/libraries/anime_movies:/data/anime_movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.jeffslord.com`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=myresolver
  # Media Organizers
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    networks:
      - traefik
    # ports:
    #   - "8989:8989"
    expose:
      - "8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/config/sonarr:/config
      - /mnt/media/libraries/shows:/data/tvshows
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/downloads:/downloads
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`sonarr.jeffslord.com`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
      
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    networks:
      - traefik
    # ports:
    #   - "7878:7878"
    expose:
      - "7878"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/radarr:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime_movies:/data/anime_movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.jeffslord.com`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=myresolver
  # Indexer
  jackett:
    image: "linuxserver/jackett:latest"
    container_name: jackett
    networks:
      - traefik
    # ports:
    #   - "9117:9117"
    expose:
      - "9117"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/config/jackett:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.jeffslord.com`)
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certresolver=myresolver
  # Downloader
  deluge:
    image: "binhex/arch-delugevpn:latest"
    container_name: deluge
    networks:
      - traefik
    cap_add:
      - NET_ADMIN
    expose:
      - "8112"
      - "8118"
      - "58846"
      - "58946"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=p9301991
      - VPN_PASS=hZkhLtbjVm
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218
      - DEBUG=false
      - UMASK=0000
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/downloads:/downloads
      - /mnt/media/config/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.jeffslord.com`)
      - traefik.http.routers.deluge.tls=true
      - traefik.http.routers.deluge.tls.certresolver=myresolver
  # Analytics
  tautulli:
    image: "linuxserver/tautulli:latest"
    container_name: tautulli
    networks:
      - traefik
    # ports:
    #   - "8181:8181"
    expose:
      - "8181"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/plexpy:/config
      - /mnt/media/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.jeffslord.com`)
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.tls.certresolver=myresolver
  # Request new media
  ombi:
    image: "linuxserver/ombi:latest"
    container_name: ombi
    networks:
      - traefik
    # ports:
        # - "3579:3579"
    expose:
      - "3579"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/ombi:/config
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`ombi.jeffslord.com`)
      - traefik.http.routers.ombi.tls=true
      - traefik.http.routers.ombi.tls.certresolver=myresolver
  # Media Portal
  muximux:
    image: "linuxserver/muximux:latest"
    container_name: muximux
    networks:
      - traefik
    expose:
      - "8079"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/muximux:/config
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.muximux.rule=Host(`muximux.jeffslord.com`)
      - traefik.http.routers.muximux.tls=true
      - traefik.http.routers.muximux.tls.certresolver=myresolver
  # Subtitles
  bazarr:
    image: "linuxserver/bazarr:latest"
    container_name: bazarr
    networks:
      - traefik
    # ports:
    #     - "6767:6767"
    expose:
      - "6767"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/bazarr:/config
      - /mnt/media/libraries/shows:/data/tvshows
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/libraries/anime_movies:/data/anime_movies
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.jeffslord.com`)
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=myresolver
  # ebooks / comics
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    networks:
     - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /mnt/media/config/ubooquity:/config
      - /mnt/media/libraries/books:/books
      - /mnt/media/libraries/comics:/comics
      - /mnt/media/libraries/raw_files:/filesi
    expose:
      - "2202"
      - "2203"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ubooquity.rule=Host(`ubooquity.jeffslord.com`)
      - traefik.http.routers.ubooquity.tls=true
      - traefik.http.routers.ubooquity.tls.certresolver=myresolver
  # audiobooks
  booksonic:
    image: linuxserver/booksonic
    container_name: booksonic
    networks:
      - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /mnt/media/config/booksonic:/config
      - /mnt/media/libraries/audiobooks:/audiobooks
      - /mnt/media/libraries/podcasts:/podcasts
      - /mnt/media/libraries/other_audio:/othermedia
    expose:
      - "4040"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.booksonic.rule=Host(`booksonic.jeffslord.com`)
      - traefik.http.routers.booksonic.tls=true
      - traefik.http.routers.booksonic.tls.certresolver=myresolver
  # groceries
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    networks:
      - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - /home/server/volumes/grocy/config:/config
    expose:
      - "9283"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.jeffslord.com`)
      - traefik.http.routers.grocy.tls=true
      - traefik.http.routers.grocy.tls.certresolver=myresolver
    restart: unless-stopped


networks:
  traefik:
    external: true
