version: "3.7"
services:
  # Media Player
  plex:
    container_name: plex
    image: "plexinc/pms-docker:latest"
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - ADVERTISE_IP=http://192.168.1.200:32400/
      - TZ=America/New_York
      - PLEX_CLAIM="claim-qxVKRrNKy9x1WQXzEJxD"
      - PLEX_UID=1000
      - PPLEX_GID=1000
    volumes:
      - /mnt/media/config/plex:/config
      - /mnt/media/transcode:/transcode
      - /mnt/media/libraries/shows:/data/tvshows
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/libraries/anime_movies:/data/anime_movies
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.plex.rule=Host(`plex.jeffslord.com`)
  # Media Organizers
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    # ports:
    #   - "8989:8989"
    expose:
      - "8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/config/sonarr:/config
      - /mnt/media/libraries/shows:/data/tv
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/downloads:/downloads
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.jeffslord.com`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    labels:
      - traefik.http.routers.sonarr.rule=Host(`sonarr.jeffslord.com`)
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    # ports:
    #   - "7878:7878"
    expose:
      - "7878"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/radarr:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime_movies:/data/anime_movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.radarr.rule=Host(`radarr.jeffslord.com`)
  # Indexer
  jackett:
    image: "linuxserver/jackett:latest"
    container_name: jackett
    # ports:
    #   - "9117:9117"
    expose:
      - "9117"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/config/jackett:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.jackett.rule=Host(`jackett.jeffslord.com`)
  # Downloader
  deluge:
    image: "binhex/arch-delugevpn:latest"
    container_name: deluge
    cap_add:
      - NET_ADMIN
    expose:
      - "8112"
      - "8118"
      - "58846"
      - "58946"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=p9301991
      - VPN_PASS=hZkhLtbjVm
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218
      - DEBUG=false
      - UMASK=0000
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/media/downloads:/downloads
      - /mnt/media/config/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.deluge.rule=Host(`deluge.jeffslord.com`)
  # Analytics
  tautulli:
    image: "linuxserver/tautulli:latest"
    container_name: tautulli
    # ports:
    #   - "8181:8181"
    expose:
      - "8181"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/plexpy:/config
      - /mnt/media/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.tautulli.rule=Host(`tautulli.jeffslord.com`)
  # Request new media
  ombi:
    image: "linuxserver/ombi:latest"
    container_name: ombi
    ports:
        - "3579:3579"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/ombi:/config
    depends_on:
      - plex
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.ombi.rule=Host(`ombi.jeffslord.com`)
  # Media Portal
  muximux:
    image: "linuxserver/muximux:latest"
    container_name: muximux
    expose:
        - "80"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/muximux:/config
    depends_on:
      - plex
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.muximux.rule=Host(`muximux.jeffslord.com`)
  # Subtitles
  bazarr:
    image: "linuxserver/bazarr:latest"
    container_name: bazarr
    ports:
        - "6767:6767"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - /mnt/media/config/bazarr:/config
      - /mnt/media/libraries/shows:/data/tvshows
      - /mnt/media/libraries/movies:/data/movies
      - /mnt/media/libraries/anime:/data/anime
      - /mnt/media/libraries/anime_movies:/data/anime_movies
    depends_on:
      - plex
    restart: unless-stopped
    networks:
      # - web
      # - media
      - traefik
    labels:
      - traefik.http.routers.bazarr.rule=Host(`bazarr.jeffslord.com`)
networks:
  traefik:
    external: true