version: "3.7"
services:
  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    networks:
      - traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.minecraft.address=:25565
      - --providers.docker=true
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesResolvers.myresolver.acme.dnsChallenge.provider=cloudflare
      # Staging server
      # - --certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.myresolver.acme.email=jeffscottlord@gmail.com
        #- --certificatesResolvers.myresolver.acme.storage=acme.json 
      - --certificatesResolvers.myresolver.acme.storage=/acme
      - --certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web
    environment:
        - CF_API_EMAIL=jeffscottord@gmail.com
        - CF_API_KEY=f5f8dc895e9b041c20296c1bb43d94fcd85b9
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # https
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /home/server/volumes/traefik/acme.json:/acme.json
      - /home/server/volumes/traefik/acme:/acme
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.jeffslord.com`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      # - traefik.http.middlewares.traefik.basicauth.users=server:$$apr1$$dmVBAsix$$7s9nj9HLlr/D0MAdvTqit1
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=myresolver

      # Global redirection: http to https
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:(www\.)?.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=wwwtohttps

      # Global redirection: https (www.) to https
      - traefik.http.routers.wwwsecure-catchall.rule=HostRegexp(`{host:(www\.).+}`)
      - traefik.http.routers.wwwsecure-catchall.entrypoints=websecure
      - traefik.http.routers.wwwsecure-catchall.tls=true
      - traefik.http.routers.wwwsecure-catchall.middlewares=wwwtohttps

      # middleware: http(s)://(www.) to  https://
      - traefik.http.middlewares.wwwtohttps.redirectregex.regex=^https?://(?:www\.)?(.+)
      - traefik.http.middlewares.wwwtohttps.redirectregex.replacement=https://$${1}
      - traefik.http.middlewares.wwwtohttps.redirectregex.permanent=true
#new
#    dns:
#      - 192.168.1.50
#      - 192.168.1.1
#
#
#  pihole:
#    container_name: pihole
#    domainname: jeffslord.com
#    image: pihole/pihole:latest
#    dns:
#      - 127.0.0.1
#      - 1.1.1.1
#    ports:
#      - '0.0.0.0:53:53/tcp'
#      - '0.0.0.0:53:53/udp'
#      - '0.0.0.0:67:67/udp'
#      - '0.0.0.0:8053:80/tcp'
#    volumes:
#      - /home/server/volumes/pihole/:/etc/pihole/
#      - /home/server/volumes/pihole/dnsmasqd:/etc/dnsmasq.d/
#    environment:
#      ServerIP: 192.168.1.50
#      PROXY_LOCATION: pihole
#      VIRTUAL_HOST: pihole.jeffslord.com
#      VIRTUAL_PORT: 80
#      TZ: 'America/Chicago'
#    restart: unless-stopped
#    labels:
#      # required when using --docker.exposedbydefault=false
#      - traefik.enable=true
#      # https://www.techjunktrunk.com/docker/2017/11/03/traefik-default-server-catch-all/
#      - "traefik.frontend.rule=HostRegexp:pihole.jeffslord.com,{catchall:.*}"
#      - "traefik.frontend.priority=1"
#      - "traefik.backend=pihole"
#      - "traefik.port=80"
#endnew
  
  test-app:
    image: containous/whoami:v1.3.0
    command:
      - --port=8082 # Our service listens on 8082
    labels:
      - traefik.enable=true
      - traefik.http.routers.test-app.rule=Host(`test.jeffslord.com`)
      - traefik.http.services.test-app.loadbalancer.server.port=8082
      # - traefik.http.middlewares.test.basicauth.users=server:$$apr1$$dmVBAsix$$7s9nj9HLlr/D0MAdvTqit1
      # - "traefik.http.middlewares.test-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
      - traefik.http.routers.test-app.tls=true
      - traefik.http.routers.test-app.entrypoints=websecure
      - traefik.http.routers.test-app.tls.certresolver=myresolver
    networks:
      - traefik

networks:
  traefik:
     name: traefik
